server:
  port: 8080
spring:
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000


qiniu:

  max-size: 15

code:
  expiration: 5

loginCode:
  expiration: 2

